# Generated by Django 5.0.6 on 2024-06-15 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_base_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='completed',
            new_name='is_completed',
        ),
    ]
